[package]
name = "girlfriend"
version = "0.2.0"
edition = "2021"
homepage = "https://uwussi.moe"
repository = "https://github.com/uwussimo/girlfriend"
description = "Girlfriend javascript for shell scripting"
authors = ["UwUssimo Robinson <uwussimo@icloud.com> (https://uwussi.moe)"]
keywords = ["girlfriend", "javascript", "shell", "scripting"]
readme = "readme.md"
categories = ["emulators", "simulation"]
license = "MIT"
exclude = ["target", ".github"]

[dependencies]
clap = "3.1.18"
deno_core = "0.145.0"
tokio = { version = "1.19.2", features = ["full"] }
